# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

commands:
  push-image-if-master:
    steps:
      - run:
          name: Push image if building master
          command: |
            if [ -n "${DOCKER_USERNAME}" ] && [ -n "${DOCKER_PASSWORD}" ]
            then
              echo "${DOCKER_PASSWORD}" | docker login -u="${DOCKER_USERNAME}" --password-stdin quay.io
              tag="test_$(git rev-parse --abbrev-ref HEAD)"
              tag=$(echo "$tag" | tr / -)
              if [ "$tag" == "test_master" ]
              then
                docker tag 3scale-kourier:test_master quay.io/3scale/kourier:master
                docker push quay.io/3scale/kourier:master
                docker tag 3scale-kourier-gateway:master quay.io/3scale/kourier-gateway:master
                docker push quay.io/3scale/kourier-gateway:master
              fi
            else
              echo "Missing docker credentials"
            fi

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /home/circleci/go/src/github.com/3scale/kourier
    steps:
      - checkout
      - run: 
          name: install goimports
          command: |
            go get golang.org/x/tools/cmd/goimports
      - run:
          name: Run formatting check
          command: |
            unmatched_files=$(goimports -l $(find . -type f -name '*.go' -not -path './vendor/*'))
            if [[ -n "${unmatched_files}" ]]
            then
              echo "Formatting issues exist. Run 'make fmt'"
              exit 1
            fi

      # Remove existing go and install 1.13.
      - run: sudo apt-get remove golang-go && sudo rm -rf /usr/local/go
      - run: wget https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz -O /tmp/go1.13.1.linux-amd64.tar.gz
      - run: sudo tar -C /usr/local -xzf /tmp/go1.13.1.linux-amd64.tar.gz
      - run: sudo snap install microk8s --classic
      - run: PATH=$PATH:/usr/local/go/bin:/snap/bin/ make test-circleci
      - push-image-if-master

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global # The docker creds are defined in this context
